apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-fetcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-fetcher
  template:
    metadata:
      labels:
        app: log-fetcher
    spec:
      containers:
      - name: log-fetcher
        image: your-registry/log-fetcher:latest
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongo-uri
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-url
        - name: ENCRYPTION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: encryption-secret
        - name: ELASTIC_URL
          value: http://elasticsearch-service:9200